# Deployment manifest for Python web application
apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-web-app
  labels:
    app: python-web-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: python-web-app

  template:
    metadata:
      labels:
        app: python-web-app

    spec:
      containers:
      - name: python-web-app
        image: "apekshaa6/python-web-app:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080